variable "vsphere_user" {}
variable "vsphere_password" {}
variable "vsphere_vcenter" {}
variable "vsphere_unverified_ssl" {}
variable "vsphere_datacenter" {}
variable "vsphere_cluster" {}
variable "vm_datastore" {}
variable "vm_network" {}
variable "vm_template" {}
variable "vm_linked_clone" {}
variable "vm_ip" {}
variable "vm_netmask" {}
variable "vm_gateway" {}
variable "vm_dns" {}
variable "vm_domain" {}
variable "vm_cpu" {}
variable "vm_ram" {}
variable "vm_name" {}